name: Output events
on: [issues, workflow_dispatch]
jobs: 
    event-info:
        runs-on: ubuntu-latest
        steps:
            -   name: Output github context
                run: echo "Github events => ${{ toJSON(github.event) }}"
    
    
    